// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/categorising/v1/categorising.proto

package bobsknobshop_category_v1

import (
	v1 "bobsknobshop/messaging/v1"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCategoryRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79e1d5934b16af15, []int{0}
}

func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(m, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

func (m *GetCategoryRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetCategoryResponse struct {
	Category             v1.MessageCategory `protobuf:"varint,2,opt,name=category,proto3,enum=bobsknobshop.messaging.v1.MessageCategory" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetCategoryResponse) Reset()         { *m = GetCategoryResponse{} }
func (m *GetCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoryResponse) ProtoMessage()    {}
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79e1d5934b16af15, []int{1}
}

func (m *GetCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryResponse.Unmarshal(m, b)
}
func (m *GetCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryResponse.Merge(m, src)
}
func (m *GetCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoryResponse.Size(m)
}
func (m *GetCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryResponse proto.InternalMessageInfo

func (m *GetCategoryResponse) GetCategory() v1.MessageCategory {
	if m != nil {
		return m.Category
	}
	return v1.MessageCategory_NONE
}

func init() {
	proto.RegisterType((*GetCategoryRequest)(nil), "bobsknobshop.category.v1.GetCategoryRequest")
	proto.RegisterType((*GetCategoryResponse)(nil), "bobsknobshop.category.v1.GetCategoryResponse")
}

func init() {
	proto.RegisterFile("bobsknobshop/categorising/v1/categorising.proto", fileDescriptor_79e1d5934b16af15)
}

var fileDescriptor_79e1d5934b16af15 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc4, 0x40,
	0x0c, 0x85, 0xad, 0x88, 0xe8, 0x28, 0x1e, 0xc6, 0x4b, 0xa9, 0x82, 0x4b, 0x2f, 0x16, 0xd1, 0x0c,
	0x5d, 0xff, 0x81, 0x0b, 0x7a, 0x12, 0x64, 0xef, 0x1e, 0x66, 0x96, 0x30, 0x56, 0xeb, 0xa4, 0x6e,
	0x62, 0x51, 0xf0, 0xc7, 0x0b, 0xdd, 0x5a, 0x3a, 0x48, 0x61, 0x6f, 0x09, 0xbc, 0x97, 0xef, 0xe5,
	0x29, 0xe3, 0xc8, 0xf1, 0x5b, 0x20, 0xc7, 0x2f, 0xd4, 0x98, 0x95, 0x15, 0xf4, 0xb4, 0xae, 0xb8,
	0x0a, 0xde, 0xb4, 0x65, 0xb4, 0x43, 0xb3, 0x26, 0x21, 0x9d, 0x8e, 0x0d, 0xd0, 0x0b, 0xbe, 0xa1,
	0x2d, 0xb3, 0x73, 0x4f, 0xe4, 0x6b, 0x34, 0xb6, 0xa9, 0x8c, 0x0d, 0x81, 0xc4, 0x4a, 0x45, 0x81,
	0x37, 0xbe, 0xec, 0x32, 0x02, 0xbd, 0x23, 0xb3, 0xf5, 0x3d, 0x85, 0xdc, 0x2b, 0xae, 0xa4, 0x17,
	0xe6, 0x85, 0xd2, 0x0f, 0x28, 0x8b, 0xfe, 0xf0, 0x12, 0x3f, 0x3e, 0x91, 0x45, 0x6b, 0xb5, 0x27,
	0xf8, 0x25, 0x69, 0x32, 0x4b, 0x8a, 0xc3, 0x65, 0x37, 0xe7, 0xcf, 0xea, 0x34, 0x52, 0x72, 0x43,
	0x81, 0x51, 0xdf, 0xab, 0x83, 0xbf, 0x58, 0xe9, 0xee, 0x2c, 0x29, 0x4e, 0xe6, 0x57, 0x10, 0x85,
	0x1e, 0xe0, 0xd0, 0x96, 0xf0, 0xd8, 0x2d, 0x38, 0x5c, 0x19, 0xbc, 0xf3, 0x1f, 0x75, 0xbc, 0x18,
	0xfd, 0xaf, 0x6b, 0x75, 0x34, 0xc2, 0xe9, 0x6b, 0x98, 0x6a, 0x02, 0xfe, 0xe7, 0xcf, 0x6e, 0xb6,
	0x54, 0x6f, 0x7e, 0xc8, 0x77, 0xee, 0x2e, 0xd4, 0x99, 0xaf, 0x27, 0x4d, 0x4f, 0x89, 0xdb, 0xef,
	0xea, 0xba, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x7a, 0xef, 0x8d, 0xc2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CategorisingClient is the client API for Categorising service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategorisingClient interface {
	// Determines sentiment for the given text.
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
}

type categorisingClient struct {
	cc *grpc.ClientConn
}

func NewCategorisingClient(cc *grpc.ClientConn) CategorisingClient {
	return &categorisingClient{cc}
}

func (c *categorisingClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.category.v1.Categorising/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategorisingServer is the server API for Categorising service.
type CategorisingServer interface {
	// Determines sentiment for the given text.
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
}

func RegisterCategorisingServer(s *grpc.Server, srv CategorisingServer) {
	s.RegisterService(&_Categorising_serviceDesc, srv)
}

func _Categorising_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategorisingServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.category.v1.Categorising/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategorisingServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Categorising_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.category.v1.Categorising",
	HandlerType: (*CategorisingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategory",
			Handler:    _Categorising_GetCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/categorising/v1/categorising.proto",
}
