// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/contact/v1/contact.proto

package contact

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateMessageRequest struct {
	// The message text.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The person sending the message.
	Sender *Sender `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// The product id (optional).
	ProductId            string   `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageRequest) Reset()         { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()    {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fa7fc10577659a8, []int{0}
}

func (m *CreateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageRequest.Unmarshal(m, b)
}
func (m *CreateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageRequest.Marshal(b, m, deterministic)
}
func (m *CreateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageRequest.Merge(m, src)
}
func (m *CreateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMessageRequest.Size(m)
}
func (m *CreateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageRequest proto.InternalMessageInfo

func (m *CreateMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateMessageRequest) GetSender() *Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *CreateMessageRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMessageRequest)(nil), "bobsknobshop.contact.v1.CreateMessageRequest")
}

func init() {
	proto.RegisterFile("bobsknobshop/contact/v1/contact.proto", fileDescriptor_2fa7fc10577659a8)
}

var fileDescriptor_2fa7fc10577659a8 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xf2, 0x09, 0x2d, 0x5d, 0xf1, 0xb2, 0x88, 0x86, 0xa8, 0x58, 0x0a, 0x42, 0x2f, 0xdd,
	0xa5, 0xf5, 0xe0, 0xc1, 0x9b, 0x45, 0x50, 0xb0, 0x20, 0x11, 0x44, 0xbc, 0xc8, 0xee, 0x66, 0xba,
	0x8d, 0x4d, 0x76, 0x62, 0x76, 0xd3, 0xd2, 0x7f, 0xe0, 0xcf, 0x16, 0x93, 0x0d, 0x28, 0x98, 0xdb,
	0xcc, 0x7b, 0x6f, 0xde, 0x3c, 0x1e, 0xb9, 0x90, 0x28, 0xed, 0xda, 0xa0, 0xb4, 0x2b, 0x2c, 0xb8,
	0x42, 0xe3, 0x84, 0x72, 0x7c, 0x33, 0x6d, 0x47, 0x56, 0x94, 0xe8, 0x90, 0x1e, 0xff, 0x94, 0xb1,
	0x96, 0xdb, 0x4c, 0xa3, 0x53, 0x8d, 0xa8, 0x33, 0xe0, 0xa2, 0x48, 0xb9, 0x30, 0x06, 0x9d, 0x70,
	0x29, 0x1a, 0xdb, 0x9c, 0x45, 0x27, 0x9e, 0xad, 0x37, 0x59, 0x2d, 0x39, 0xe4, 0x85, 0xdb, 0x79,
	0xb2, 0xf3, 0x35, 0xca, 0x77, 0x50, 0xce, 0x7b, 0x8c, 0x3e, 0x03, 0x72, 0x38, 0x2f, 0x41, 0x38,
	0x58, 0x80, 0xb5, 0x42, 0x43, 0x0c, 0x1f, 0x15, 0x58, 0x47, 0x43, 0xd2, 0xcf, 0x1b, 0x24, 0x0c,
	0x86, 0xc1, 0x78, 0x10, 0xb7, 0x2b, 0xbd, 0x22, 0x3d, 0x0b, 0x26, 0x81, 0x32, 0xfc, 0x3f, 0x0c,
	0xc6, 0xfb, 0xb3, 0x73, 0xd6, 0x11, 0x9f, 0x3d, 0xd5, 0xb2, 0xd8, 0xcb, 0xe9, 0x19, 0x21, 0x45,
	0x89, 0x49, 0xa5, 0xdc, 0x5b, 0x9a, 0x84, 0x7b, 0xb5, 0xeb, 0xc0, 0x23, 0xf7, 0xc9, 0x4c, 0x91,
	0xfe, 0xbc, 0xb9, 0xa5, 0x2f, 0xe4, 0xe0, 0x57, 0x28, 0x3a, 0xe9, 0xfc, 0xf1, 0x57, 0xf8, 0xe8,
	0x88, 0x35, 0xd5, 0xb0, 0xb6, 0x1a, 0x76, 0xfb, 0x5d, 0xcd, 0xe8, 0xdf, 0x4d, 0x4e, 0x22, 0x9d,
	0x75, 0x99, 0x3d, 0x06, 0xaf, 0x0b, 0x9d, 0xba, 0x55, 0x25, 0x99, 0xc2, 0x9c, 0xdf, 0x89, 0x1d,
	0x3e, 0x0b, 0xf3, 0x80, 0x68, 0x9a, 0x8e, 0xb7, 0x58, 0xae, 0x97, 0x19, 0x6e, 0x27, 0x1a, 0x4c,
	0x0d, 0xf0, 0x8e, 0x92, 0xaf, 0xfd, 0x28, 0x7b, 0xb5, 0xec, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0xdb, 0x3b, 0xc1, 0xf6, 0x09, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactClient is the client API for Contact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactClient interface {
	// Stores a new message.
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type contactClient struct {
	cc *grpc.ClientConn
}

func NewContactClient(cc *grpc.ClientConn) ContactClient {
	return &contactClient{cc}
}

func (c *contactClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bobsknobshop.contact.v1.Contact/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServer is the server API for Contact service.
type ContactServer interface {
	// Stores a new message.
	CreateMessage(context.Context, *CreateMessageRequest) (*empty.Empty, error)
}

func RegisterContactServer(s *grpc.Server, srv ContactServer) {
	s.RegisterService(&_Contact_serviceDesc, srv)
}

func _Contact_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.contact.v1.Contact/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contact_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.contact.v1.Contact",
	HandlerType: (*ContactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _Contact_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/contact/v1/contact.proto",
}
