// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/messaging/v1/objects.proto

package bobsknobshop_messaging_v1

import (
	v1 "bobsknobshop/contact/v1"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// An enumeration of message categories.
type MessageCategory int32

const (
	// Not yet analysed.
	MessageCategory_NONE MessageCategory = 0
	// A question that should be answered.
	MessageCategory_QUESTION MessageCategory = 1
	// A complaint that should be addressed.
	MessageCategory_COMPLAINT MessageCategory = 2
	// Feedback, positive or negative, with no need for (immediate) replies.
	// Use cases include (process) improvement analysis or website
	// endorsement content.
	MessageCategory_FEEDBACK MessageCategory = 3
	// Messages defying the current classification scheme.
	MessageCategory_OTHER MessageCategory = 4
	// Junk
	MessageCategory_GARBAGE MessageCategory = 99
)

var MessageCategory_name = map[int32]string{
	0:  "NONE",
	1:  "QUESTION",
	2:  "COMPLAINT",
	3:  "FEEDBACK",
	4:  "OTHER",
	99: "GARBAGE",
}

var MessageCategory_value = map[string]int32{
	"NONE":      0,
	"QUESTION":  1,
	"COMPLAINT": 2,
	"FEEDBACK":  3,
	"OTHER":     4,
	"GARBAGE":   99,
}

func (x MessageCategory) String() string {
	return proto.EnumName(MessageCategory_name, int32(x))
}

func (MessageCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40fb2f0e1e88f56b, []int{0}
}

// A message status enum.
type Status int32

const (
	// No processing initiated or aborted without results.
	Status_TO_DO Status = 0
	// Message is being processed.
	Status_IN_PROCESS Status = 1
	// Message processing has been put on hold.
	Status_ON_HOLD Status = 2
	// Message processing has been completed.
	Status_DONE Status = 3
	// Message has been discarded.
	Status_DISCARDED Status = 99
)

var Status_name = map[int32]string{
	0:  "TO_DO",
	1:  "IN_PROCESS",
	2:  "ON_HOLD",
	3:  "DONE",
	99: "DISCARDED",
}

var Status_value = map[string]int32{
	"TO_DO":      0,
	"IN_PROCESS": 1,
	"ON_HOLD":    2,
	"DONE":       3,
	"DISCARDED":  99,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40fb2f0e1e88f56b, []int{1}
}

// A message sent by a customer or prospect.
type CustomerMessage struct {
	// The message text.
	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// The customer.
	Sender *v1.Sender `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Message category implying course of action.
	Category MessageCategory `protobuf:"varint,3,opt,name=category,proto3,enum=bobsknobshop.messaging.v1.MessageCategory" json:"category,omitempty"`
	// Message handling status.
	Status               Status   `protobuf:"varint,4,opt,name=status,proto3,enum=bobsknobshop.messaging.v1.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerMessage) Reset()         { *m = CustomerMessage{} }
func (m *CustomerMessage) String() string { return proto.CompactTextString(m) }
func (*CustomerMessage) ProtoMessage()    {}
func (*CustomerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fb2f0e1e88f56b, []int{0}
}

func (m *CustomerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerMessage.Unmarshal(m, b)
}
func (m *CustomerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerMessage.Marshal(b, m, deterministic)
}
func (m *CustomerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerMessage.Merge(m, src)
}
func (m *CustomerMessage) XXX_Size() int {
	return xxx_messageInfo_CustomerMessage.Size(m)
}
func (m *CustomerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerMessage proto.InternalMessageInfo

func (m *CustomerMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CustomerMessage) GetSender() *v1.Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *CustomerMessage) GetCategory() MessageCategory {
	if m != nil {
		return m.Category
	}
	return MessageCategory_NONE
}

func (m *CustomerMessage) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_TO_DO
}

func init() {
	proto.RegisterEnum("bobsknobshop.messaging.v1.MessageCategory", MessageCategory_name, MessageCategory_value)
	proto.RegisterEnum("bobsknobshop.messaging.v1.Status", Status_name, Status_value)
	proto.RegisterType((*CustomerMessage)(nil), "bobsknobshop.messaging.v1.CustomerMessage")
}

func init() {
	proto.RegisterFile("bobsknobshop/messaging/v1/objects.proto", fileDescriptor_40fb2f0e1e88f56b)
}

var fileDescriptor_40fb2f0e1e88f56b = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0xef, 0xd2, 0x30,
	0x1c, 0xc6, 0x29, 0xcc, 0x09, 0x5f, 0x14, 0x9a, 0x9e, 0xa6, 0x31, 0x71, 0x9a, 0x18, 0x09, 0x87,
	0x12, 0xf0, 0x60, 0x3c, 0x8e, 0xad, 0xc0, 0x22, 0xac, 0xd8, 0xcd, 0xab, 0x64, 0x1b, 0xcb, 0xfc,
	0xc7, 0x4a, 0xd6, 0x42, 0xc2, 0xcb, 0xf5, 0x9d, 0x98, 0xcd, 0x85, 0x88, 0x86, 0xdf, 0xad, 0x49,
	0x3f, 0xcf, 0xe7, 0x79, 0x9a, 0xc2, 0xdb, 0x44, 0x26, 0xea, 0x47, 0x21, 0x13, 0xf5, 0x55, 0x1e,
	0x27, 0x87, 0x4c, 0xa9, 0x38, 0xff, 0x56, 0xe4, 0x93, 0xf3, 0x74, 0x22, 0x93, 0xef, 0x59, 0xaa,
	0x15, 0x3d, 0x96, 0x52, 0x4b, 0xf2, 0xec, 0x6f, 0x90, 0x5e, 0x41, 0x7a, 0x9e, 0x3e, 0x7f, 0x73,
	0xe3, 0x48, 0x65, 0xa1, 0xe3, 0x54, 0xff, 0x67, 0x78, 0xfd, 0x0b, 0xc1, 0xd0, 0x3d, 0x29, 0x2d,
	0x0f, 0x59, 0xb9, 0xa9, 0xf3, 0x19, 0x21, 0x60, 0x24, 0x72, 0x7f, 0xb1, 0x90, 0x8d, 0x46, 0x3d,
	0x51, 0x9f, 0xc9, 0x7b, 0x30, 0x55, 0x56, 0xec, 0xb3, 0xd2, 0x6a, 0xdb, 0x68, 0xd4, 0x9f, 0xbd,
	0xa4, 0x37, 0xd5, 0x8d, 0x9f, 0x9e, 0xa7, 0x34, 0xac, 0x31, 0xd1, 0xe0, 0x64, 0x01, 0xdd, 0x34,
	0xd6, 0x59, 0x2e, 0xcb, 0x8b, 0xd5, 0xb1, 0xd1, 0x68, 0x30, 0x1b, 0xd3, 0xbb, 0xab, 0x69, 0x33,
	0xc1, 0x6d, 0x12, 0xe2, 0x9a, 0x25, 0x1f, 0xc0, 0x54, 0x3a, 0xd6, 0x27, 0x65, 0x19, 0xb5, 0xe5,
	0xd5, 0x03, 0x96, 0xb0, 0x06, 0x45, 0x13, 0x18, 0x7f, 0x81, 0xe1, 0x3f, 0x5e, 0xd2, 0x05, 0x23,
	0xe0, 0x01, 0xc3, 0x2d, 0xf2, 0x04, 0xba, 0x9f, 0x3e, 0xb3, 0x30, 0xf2, 0x79, 0x80, 0x11, 0x79,
	0x0a, 0x3d, 0x97, 0x6f, 0xb6, 0x6b, 0xc7, 0x0f, 0x22, 0xdc, 0xae, 0x2e, 0x17, 0x8c, 0x79, 0x73,
	0xc7, 0xfd, 0x88, 0x3b, 0xa4, 0x07, 0x8f, 0x78, 0xb4, 0x62, 0x02, 0x1b, 0xa4, 0x0f, 0x8f, 0x97,
	0x8e, 0x98, 0x3b, 0x4b, 0x86, 0xd3, 0xb1, 0x0f, 0xe6, 0x9f, 0xc6, 0x8a, 0x88, 0xf8, 0xce, 0xe3,
	0xb8, 0x45, 0x06, 0x00, 0x7e, 0xb0, 0xdb, 0x0a, 0xee, 0xb2, 0x30, 0xc4, 0xa8, 0x4a, 0xf0, 0x60,
	0xb7, 0xe2, 0x6b, 0x0f, 0xb7, 0xab, 0x7a, 0xaf, 0xaa, 0xef, 0x54, 0x85, 0x9e, 0x1f, 0xba, 0x8e,
	0xf0, 0x98, 0x87, 0xd3, 0xb9, 0x0d, 0x2f, 0xf2, 0x9f, 0xf7, 0x5f, 0xb6, 0x45, 0x89, 0x59, 0xff,
	0xdb, 0xbb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x04, 0x88, 0x40, 0x1a, 0x24, 0x02, 0x00, 0x00,
}
