// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/storage/v1/storage.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostObjectRequest struct {
	// Key to store data by.
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Data to store.
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostObjectRequest) Reset()         { *m = PostObjectRequest{} }
func (m *PostObjectRequest) String() string { return proto.CompactTextString(m) }
func (*PostObjectRequest) ProtoMessage()    {}
func (*PostObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{0}
}

func (m *PostObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostObjectRequest.Unmarshal(m, b)
}
func (m *PostObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostObjectRequest.Marshal(b, m, deterministic)
}
func (m *PostObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostObjectRequest.Merge(m, src)
}
func (m *PostObjectRequest) XXX_Size() int {
	return xxx_messageInfo_PostObjectRequest.Size(m)
}
func (m *PostObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostObjectRequest proto.InternalMessageInfo

func (m *PostObjectRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PostObjectRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostObjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostObjectResponse) Reset()         { *m = PostObjectResponse{} }
func (m *PostObjectResponse) String() string { return proto.CompactTextString(m) }
func (*PostObjectResponse) ProtoMessage()    {}
func (*PostObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{1}
}

func (m *PostObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostObjectResponse.Unmarshal(m, b)
}
func (m *PostObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostObjectResponse.Marshal(b, m, deterministic)
}
func (m *PostObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostObjectResponse.Merge(m, src)
}
func (m *PostObjectResponse) XXX_Size() int {
	return xxx_messageInfo_PostObjectResponse.Size(m)
}
func (m *PostObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostObjectResponse proto.InternalMessageInfo

type GetObjectRequest struct {
	// Keys of data to retrieve.
	// Keys may contain wildcards.
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{2}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetObjectResponse struct {
	// Keys of found objects.
	// May be smaller than keys in request.
	// Indexes match data list elements
	Keys []*Key `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Data matching keys.
	// Indexes match keys list elements
	Data                 [][]byte `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{3}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetObjectResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteObjectRequest struct {
	// Keys of data to delete.
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectRequest) Reset()         { *m = DeleteObjectRequest{} }
func (m *DeleteObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectRequest) ProtoMessage()    {}
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{4}
}

func (m *DeleteObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectRequest.Unmarshal(m, b)
}
func (m *DeleteObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectRequest.Merge(m, src)
}
func (m *DeleteObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectRequest.Size(m)
}
func (m *DeleteObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectRequest proto.InternalMessageInfo

func (m *DeleteObjectRequest) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Key struct {
	// A key consists of a list of key-values.
	Parts                []*Key_Part `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{5}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetParts() []*Key_Part {
	if m != nil {
		return m.Parts
	}
	return nil
}

type Key_Part struct {
	// Key names starting with underscores are reserved.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The wildcard character '*' is reserved and may not be used as a
	// storage key value.
	// Can be set to the wildcard character '*' in queries.
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key_Part) Reset()         { *m = Key_Part{} }
func (m *Key_Part) String() string { return proto.CompactTextString(m) }
func (*Key_Part) ProtoMessage()    {}
func (*Key_Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{5, 0}
}

func (m *Key_Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_Part.Unmarshal(m, b)
}
func (m *Key_Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_Part.Marshal(b, m, deterministic)
}
func (m *Key_Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_Part.Merge(m, src)
}
func (m *Key_Part) XXX_Size() int {
	return xxx_messageInfo_Key_Part.Size(m)
}
func (m *Key_Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Key_Part proto.InternalMessageInfo

func (m *Key_Part) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Key_Part) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*PostObjectRequest)(nil), "bobsknobshop.storage.v1.PostObjectRequest")
	proto.RegisterType((*PostObjectResponse)(nil), "bobsknobshop.storage.v1.PostObjectResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "bobsknobshop.storage.v1.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "bobsknobshop.storage.v1.GetObjectResponse")
	proto.RegisterType((*DeleteObjectRequest)(nil), "bobsknobshop.storage.v1.DeleteObjectRequest")
	proto.RegisterType((*Key)(nil), "bobsknobshop.storage.v1.Key")
	proto.RegisterType((*Key_Part)(nil), "bobsknobshop.storage.v1.Key.Part")
}

func init() {
	proto.RegisterFile("bobsknobshop/storage/v1/storage.proto", fileDescriptor_080033004dab5fe1)
}

var fileDescriptor_080033004dab5fe1 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xde, 0x6e, 0x59, 0x0d, 0xcf, 0x3d, 0xec, 0x8e, 0x1b, 0x25, 0x75, 0x0f, 0xd8, 0xc4, 0x64,
	0x45, 0x9d, 0x0a, 0x1e, 0xbc, 0x1b, 0x08, 0x26, 0x98, 0x48, 0x6a, 0x82, 0xd1, 0xdb, 0x14, 0x1e,
	0x05, 0x5b, 0xe6, 0xd5, 0xce, 0x14, 0xd2, 0xff, 0xca, 0x3f, 0xd1, 0xd0, 0xa1, 0xd0, 0xa0, 0x55,
	0x8c, 0xb7, 0x4e, 0xdf, 0xf7, 0xe3, 0xe5, 0x7d, 0xf9, 0xe0, 0x59, 0x40, 0x81, 0x8a, 0x24, 0x05,
	0x6a, 0x41, 0x89, 0xa7, 0x34, 0xa5, 0x22, 0x44, 0x6f, 0xdd, 0x2d, 0x3f, 0x79, 0x92, 0x92, 0x26,
	0xf6, 0xb8, 0x0a, 0xe3, 0xe5, 0x6c, 0xdd, 0x75, 0x9e, 0x84, 0x44, 0x61, 0x8c, 0x5e, 0x01, 0x0b,
	0xb2, 0xb9, 0x87, 0xab, 0x44, 0xe7, 0x86, 0xe5, 0xdc, 0xee, 0x86, 0x22, 0x59, 0x7a, 0x42, 0x4a,
	0xd2, 0x42, 0x2f, 0x49, 0x2a, 0x33, 0x75, 0x3f, 0xc3, 0xf5, 0x98, 0x94, 0xfe, 0x18, 0x7c, 0xc3,
	0xa9, 0xf6, 0xf1, 0x7b, 0x86, 0x4a, 0x33, 0x0e, 0x76, 0x84, 0x79, 0xcb, 0x6a, 0x5b, 0x77, 0x0f,
	0x7a, 0xb7, 0xbc, 0xc6, 0x96, 0x8f, 0x30, 0xf7, 0xb7, 0x40, 0xc6, 0xa0, 0x31, 0x13, 0x5a, 0xb4,
	0xce, 0xdb, 0xd6, 0xdd, 0xa5, 0x5f, 0x7c, 0xbb, 0x37, 0xc0, 0xaa, 0xc2, 0x2a, 0x21, 0xa9, 0xd0,
	0xed, 0xc3, 0xd5, 0x10, 0x8f, 0xdc, 0x5e, 0x43, 0x23, 0xc2, 0x5c, 0xb5, 0xac, 0xb6, 0xfd, 0x57,
	0xbb, 0x02, 0xe9, 0x7e, 0x81, 0xeb, 0x8a, 0x8a, 0x91, 0xfe, 0x77, 0x99, 0xca, 0xda, 0xf6, 0x7e,
	0xed, 0x21, 0x3c, 0xec, 0x63, 0x8c, 0x1a, 0xff, 0x77, 0x47, 0x09, 0xf6, 0x08, 0x73, 0xf6, 0x16,
	0x2e, 0x12, 0x91, 0xea, 0x92, 0xf9, 0xf4, 0x4f, 0x4c, 0x3e, 0x16, 0xa9, 0xf6, 0x0d, 0xde, 0xe1,
	0xd0, 0xd8, 0x3e, 0xd9, 0xd5, 0x21, 0x8b, 0xa6, 0xb9, 0xf6, 0x0d, 0x5c, 0xac, 0x45, 0x9c, 0x61,
	0x71, 0xee, 0xa6, 0x6f, 0x1e, 0xbd, 0x1f, 0xe7, 0x70, 0xff, 0x93, 0x91, 0x63, 0x21, 0xc0, 0xe1,
	0xf6, 0xac, 0x53, 0xeb, 0xf9, 0x4b, 0xf2, 0xce, 0x8b, 0x93, 0xb0, 0xbb, 0x30, 0xcf, 0xd8, 0x0c,
	0x9a, 0xfb, 0x20, 0xd8, 0xf3, 0x5a, 0xee, 0x71, 0xe4, 0x4e, 0xe7, 0x14, 0xe8, 0xde, 0x65, 0x02,
	0x97, 0xd5, 0x4c, 0xd8, 0xcb, 0x5a, 0xf6, 0x6f, 0xa2, 0x73, 0x1e, 0x71, 0x53, 0x00, 0x5e, 0xb6,
	0x83, 0x0f, 0xb6, 0xed, 0x70, 0xcf, 0xde, 0x21, 0x38, 0x61, 0x5c, 0xa7, 0x35, 0xb6, 0xbe, 0x0e,
	0xc2, 0xa5, 0x5e, 0x64, 0x01, 0x9f, 0xd2, 0xca, 0x7b, 0x2f, 0x72, 0x9a, 0x08, 0xf9, 0x81, 0x48,
	0x9a, 0x9a, 0x6d, 0x28, 0x8d, 0xe6, 0x31, 0x6d, 0x5e, 0x85, 0x28, 0x8b, 0x1f, 0x5e, 0x4d, 0x89,
	0x83, 0x7b, 0xc5, 0xf8, 0xcd, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xea, 0xbc, 0xa2, 0xe6,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	// Stores or updates data by a given key.
	PostObject(ctx context.Context, in *PostObjectRequest, opts ...grpc.CallOption) (*PostObjectResponse, error)
	// Retrieves one or more data by key(s).
	// Keys may contain wildcard values.
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	// Deletes data.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) PostObject(ctx context.Context, in *PostObjectRequest, opts ...grpc.CallOption) (*PostObjectResponse, error) {
	out := new(PostObjectResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/PostObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	// Stores or updates data by a given key.
	PostObject(context.Context, *PostObjectRequest) (*PostObjectResponse, error)
	// Retrieves one or more data by key(s).
	// Keys may contain wildcard values.
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	// Deletes data.
	DeleteObject(context.Context, *DeleteObjectRequest) (*empty.Empty, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_PostObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).PostObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/PostObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).PostObject(ctx, req.(*PostObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.storage.v1.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostObject",
			Handler:    _Storage_PostObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _Storage_GetObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _Storage_DeleteObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/storage/v1/storage.proto",
}
