// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/storage/v1/storage.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateObjectRequest struct {
	// Key to store data by.
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Data to store.
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateObjectRequest) Reset()         { *m = CreateObjectRequest{} }
func (m *CreateObjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateObjectRequest) ProtoMessage()    {}
func (*CreateObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{0}
}

func (m *CreateObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectRequest.Unmarshal(m, b)
}
func (m *CreateObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectRequest.Merge(m, src)
}
func (m *CreateObjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateObjectRequest.Size(m)
}
func (m *CreateObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectRequest proto.InternalMessageInfo

func (m *CreateObjectRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CreateObjectRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateObjectResponse struct {
	// Name by which object is stored.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The object's etag, calculated over the object data
	Etag                 string   `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateObjectResponse) Reset()         { *m = CreateObjectResponse{} }
func (m *CreateObjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateObjectResponse) ProtoMessage()    {}
func (*CreateObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{1}
}

func (m *CreateObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectResponse.Unmarshal(m, b)
}
func (m *CreateObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectResponse.Merge(m, src)
}
func (m *CreateObjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateObjectResponse.Size(m)
}
func (m *CreateObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectResponse proto.InternalMessageInfo

func (m *CreateObjectResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateObjectResponse) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type GetObjectRequest struct {
	// Keys of data to retrieve.
	// Keys may contain wildcards.
	Keys []*Key `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	// Maximum number of items returned.
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{2}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetObjectRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetObjectResponse struct {
	Entries              []*GetObjectResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{3}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetEntries() []*GetObjectResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetObjectResponse_Entry struct {
	// The object's key
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The object's etag, calculated over the data
	Etag string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	// The data
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse_Entry) Reset()         { *m = GetObjectResponse_Entry{} }
func (m *GetObjectResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse_Entry) ProtoMessage()    {}
func (*GetObjectResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{3, 0}
}

func (m *GetObjectResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse_Entry.Unmarshal(m, b)
}
func (m *GetObjectResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse_Entry.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse_Entry.Merge(m, src)
}
func (m *GetObjectResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse_Entry.Size(m)
}
func (m *GetObjectResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse_Entry proto.InternalMessageInfo

func (m *GetObjectResponse_Entry) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetObjectResponse_Entry) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *GetObjectResponse_Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteObjectRequest struct {
	// Keys of data to delete.
	// Uses exact keys.
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectRequest) Reset()         { *m = DeleteObjectRequest{} }
func (m *DeleteObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectRequest) ProtoMessage()    {}
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{4}
}

func (m *DeleteObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectRequest.Unmarshal(m, b)
}
func (m *DeleteObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectRequest.Merge(m, src)
}
func (m *DeleteObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectRequest.Size(m)
}
func (m *DeleteObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectRequest proto.InternalMessageInfo

func (m *DeleteObjectRequest) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type MutateObjectRequest struct {
	OldKey               *Key     `protobuf:"bytes,1,opt,name=old_key,json=oldKey,proto3" json:"old_key,omitempty"`
	NewKey               *Key     `protobuf:"bytes,2,opt,name=new_key,json=newKey,proto3" json:"new_key,omitempty"`
	OldEtag              string   `protobuf:"bytes,3,opt,name=old_etag,json=oldEtag,proto3" json:"old_etag,omitempty"`
	NewData              []byte   `protobuf:"bytes,4,opt,name=new_data,json=newData,proto3" json:"new_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateObjectRequest) Reset()         { *m = MutateObjectRequest{} }
func (m *MutateObjectRequest) String() string { return proto.CompactTextString(m) }
func (*MutateObjectRequest) ProtoMessage()    {}
func (*MutateObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{5}
}

func (m *MutateObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateObjectRequest.Unmarshal(m, b)
}
func (m *MutateObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateObjectRequest.Marshal(b, m, deterministic)
}
func (m *MutateObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateObjectRequest.Merge(m, src)
}
func (m *MutateObjectRequest) XXX_Size() int {
	return xxx_messageInfo_MutateObjectRequest.Size(m)
}
func (m *MutateObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutateObjectRequest proto.InternalMessageInfo

func (m *MutateObjectRequest) GetOldKey() *Key {
	if m != nil {
		return m.OldKey
	}
	return nil
}

func (m *MutateObjectRequest) GetNewKey() *Key {
	if m != nil {
		return m.NewKey
	}
	return nil
}

func (m *MutateObjectRequest) GetOldEtag() string {
	if m != nil {
		return m.OldEtag
	}
	return ""
}

func (m *MutateObjectRequest) GetNewData() []byte {
	if m != nil {
		return m.NewData
	}
	return nil
}

type MutateObjectResponse struct {
	NewEtag              string   `protobuf:"bytes,2,opt,name=new_etag,json=newEtag,proto3" json:"new_etag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateObjectResponse) Reset()         { *m = MutateObjectResponse{} }
func (m *MutateObjectResponse) String() string { return proto.CompactTextString(m) }
func (*MutateObjectResponse) ProtoMessage()    {}
func (*MutateObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{6}
}

func (m *MutateObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateObjectResponse.Unmarshal(m, b)
}
func (m *MutateObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateObjectResponse.Marshal(b, m, deterministic)
}
func (m *MutateObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateObjectResponse.Merge(m, src)
}
func (m *MutateObjectResponse) XXX_Size() int {
	return xxx_messageInfo_MutateObjectResponse.Size(m)
}
func (m *MutateObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutateObjectResponse proto.InternalMessageInfo

func (m *MutateObjectResponse) GetNewEtag() string {
	if m != nil {
		return m.NewEtag
	}
	return ""
}

type GetStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{7}
}

func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

type GetStatsResponse struct {
	NumItems             int32    `protobuf:"varint,1,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsResponse) Reset()         { *m = GetStatsResponse{} }
func (m *GetStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatsResponse) ProtoMessage()    {}
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{8}
}

func (m *GetStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsResponse.Unmarshal(m, b)
}
func (m *GetStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsResponse.Merge(m, src)
}
func (m *GetStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatsResponse.Size(m)
}
func (m *GetStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsResponse proto.InternalMessageInfo

func (m *GetStatsResponse) GetNumItems() int32 {
	if m != nil {
		return m.NumItems
	}
	return 0
}

type Key struct {
	// Name by which object is stored.
	// Output only
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A key consists of a list of key-values.
	Parts []*Key_Part `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	// Additional search keys
	IndexedValues        []*Key_Part `protobuf:"bytes,3,rep,name=indexed_values,json=indexedValues,proto3" json:"indexed_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{9}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Key) GetParts() []*Key_Part {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *Key) GetIndexedValues() []*Key_Part {
	if m != nil {
		return m.IndexedValues
	}
	return nil
}

type Key_Part struct {
	// Must not contain '=' or '~'
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The wildcard character '*' is reserved and may not be used when
	// storing values.
	// Can be set to the wildcard character '*' in queries.
	// Must not contain '=' or '~'
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key_Part) Reset()         { *m = Key_Part{} }
func (m *Key_Part) String() string { return proto.CompactTextString(m) }
func (*Key_Part) ProtoMessage()    {}
func (*Key_Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_080033004dab5fe1, []int{9, 0}
}

func (m *Key_Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_Part.Unmarshal(m, b)
}
func (m *Key_Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_Part.Marshal(b, m, deterministic)
}
func (m *Key_Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_Part.Merge(m, src)
}
func (m *Key_Part) XXX_Size() int {
	return xxx_messageInfo_Key_Part.Size(m)
}
func (m *Key_Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Key_Part proto.InternalMessageInfo

func (m *Key_Part) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Key_Part) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateObjectRequest)(nil), "bobsknobshop.storage.v1.CreateObjectRequest")
	proto.RegisterType((*CreateObjectResponse)(nil), "bobsknobshop.storage.v1.CreateObjectResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "bobsknobshop.storage.v1.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "bobsknobshop.storage.v1.GetObjectResponse")
	proto.RegisterType((*GetObjectResponse_Entry)(nil), "bobsknobshop.storage.v1.GetObjectResponse.Entry")
	proto.RegisterType((*DeleteObjectRequest)(nil), "bobsknobshop.storage.v1.DeleteObjectRequest")
	proto.RegisterType((*MutateObjectRequest)(nil), "bobsknobshop.storage.v1.MutateObjectRequest")
	proto.RegisterType((*MutateObjectResponse)(nil), "bobsknobshop.storage.v1.MutateObjectResponse")
	proto.RegisterType((*GetStatsRequest)(nil), "bobsknobshop.storage.v1.GetStatsRequest")
	proto.RegisterType((*GetStatsResponse)(nil), "bobsknobshop.storage.v1.GetStatsResponse")
	proto.RegisterType((*Key)(nil), "bobsknobshop.storage.v1.Key")
	proto.RegisterType((*Key_Part)(nil), "bobsknobshop.storage.v1.Key.Part")
}

func init() {
	proto.RegisterFile("bobsknobshop/storage/v1/storage.proto", fileDescriptor_080033004dab5fe1)
}

var fileDescriptor_080033004dab5fe1 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x51, 0x4f, 0xd4, 0x40,
	0x10, 0xbe, 0xd2, 0x3b, 0xb8, 0x1b, 0x51, 0x61, 0xb9, 0xe8, 0x51, 0x78, 0x38, 0x9b, 0x98, 0x1c,
	0x46, 0x5a, 0xc0, 0x18, 0x1f, 0x4c, 0x7c, 0x50, 0x08, 0x28, 0x12, 0x49, 0x49, 0x48, 0xe4, 0xe5,
	0xb2, 0xe5, 0x86, 0x52, 0xaf, 0xdd, 0x3d, 0xdb, 0x2d, 0x67, 0xff, 0x81, 0x7f, 0xc9, 0x37, 0x7f,
	0x80, 0x3f, 0xca, 0xec, 0xb6, 0xc5, 0x02, 0x77, 0x67, 0xf5, 0x6d, 0x3a, 0x3b, 0xdf, 0x37, 0x33,
	0xdf, 0xce, 0x6c, 0xe1, 0xa9, 0xcb, 0xdd, 0x78, 0xc8, 0xb8, 0x1b, 0x5f, 0xf2, 0x91, 0x1d, 0x0b,
	0x1e, 0x51, 0x0f, 0xed, 0xab, 0xed, 0xc2, 0xb4, 0x46, 0x11, 0x17, 0x9c, 0x3c, 0x2e, 0x87, 0x59,
	0xc5, 0xd9, 0xd5, 0xb6, 0xb1, 0xe6, 0x71, 0xee, 0x05, 0x68, 0xab, 0x30, 0x37, 0xb9, 0xb0, 0x31,
	0x1c, 0x89, 0x34, 0x43, 0x19, 0xeb, 0xf9, 0x21, 0x1d, 0xf9, 0x36, 0x65, 0x8c, 0x0b, 0x2a, 0x7c,
	0xce, 0xe2, 0xec, 0xd4, 0xfc, 0x0c, 0x2b, 0xef, 0x22, 0xa4, 0x02, 0x3f, 0xb9, 0x5f, 0xf0, 0x5c,
	0x38, 0xf8, 0x35, 0xc1, 0x58, 0x10, 0x0b, 0xf4, 0x21, 0xa6, 0x1d, 0xad, 0xab, 0xf5, 0xee, 0xed,
	0xac, 0x5b, 0x53, 0x12, 0x5b, 0x87, 0x98, 0x3a, 0x32, 0x90, 0x10, 0xa8, 0x0f, 0xa8, 0xa0, 0x9d,
	0xb9, 0xae, 0xd6, 0x5b, 0x74, 0x94, 0x6d, 0xbe, 0x81, 0xf6, 0x4d, 0xea, 0x78, 0xc4, 0x59, 0x8c,
	0x32, 0x96, 0xd1, 0x10, 0x15, 0x79, 0xcb, 0x51, 0xb6, 0xf4, 0xa1, 0xa0, 0x9e, 0xc2, 0xb7, 0x1c,
	0x65, 0x9b, 0x67, 0xb0, 0xb4, 0x8f, 0xe2, 0x66, 0x5d, 0x5b, 0x50, 0x1f, 0x62, 0x1a, 0x77, 0xb4,
	0xae, 0xfe, 0xd7, 0xc2, 0x54, 0x24, 0x69, 0x43, 0x23, 0xf0, 0x43, 0x5f, 0x74, 0xf4, 0xae, 0xd6,
	0x6b, 0x38, 0xd9, 0x87, 0xf9, 0x53, 0x83, 0xe5, 0x12, 0x79, 0x5e, 0xd9, 0x07, 0x58, 0x40, 0x26,
	0x22, 0x1f, 0x8b, 0x04, 0x5b, 0x53, 0x13, 0xdc, 0x01, 0x5b, 0x7b, 0x4c, 0x44, 0xa9, 0x53, 0x10,
	0x18, 0x7d, 0x68, 0x28, 0xcf, 0xff, 0x48, 0x79, 0x5b, 0x8a, 0x6b, 0x79, 0xf5, 0x92, 0xbc, 0xfb,
	0xb0, 0xb2, 0x8b, 0x01, 0xde, 0xbe, 0xb9, 0x7f, 0x56, 0xc8, 0xfc, 0xa1, 0xc1, 0xca, 0x51, 0x22,
	0xee, 0xcc, 0xc0, 0x4b, 0x58, 0xe0, 0xc1, 0xa0, 0x5f, 0xb5, 0xf8, 0x79, 0x1e, 0x0c, 0x0e, 0x31,
	0x95, 0x30, 0x86, 0x63, 0x05, 0x9b, 0xab, 0x02, 0x63, 0x38, 0x96, 0xb0, 0x55, 0x68, 0xca, 0x6c,
	0xaa, 0x75, 0x5d, 0xb5, 0x2e, 0xb3, 0xef, 0xc9, 0xee, 0x57, 0xa1, 0x29, 0x19, 0x95, 0x02, 0x75,
	0xa5, 0x80, 0xcc, 0xb0, 0x2b, 0x45, 0xd8, 0x86, 0xf6, 0xcd, 0xd2, 0xf3, 0x9b, 0xcc, 0x21, 0x25,
	0x21, 0x25, 0x44, 0xb2, 0x99, 0xcb, 0xf0, 0x70, 0x1f, 0xc5, 0x89, 0xa0, 0x22, 0xce, 0x3b, 0x35,
	0x6d, 0x35, 0x69, 0xb9, 0x2b, 0x67, 0x58, 0x83, 0x16, 0x4b, 0xc2, 0xbe, 0x2f, 0x30, 0x8c, 0x55,
	0xff, 0x0d, 0xa7, 0xc9, 0x92, 0xf0, 0xbd, 0xfc, 0x36, 0x7f, 0x69, 0xa0, 0x1f, 0x66, 0x77, 0x75,
	0x67, 0x94, 0x5f, 0x41, 0x63, 0x44, 0x23, 0x11, 0x77, 0xe6, 0xd4, 0x0d, 0x3c, 0x99, 0xd5, 0xbd,
	0x75, 0x4c, 0x23, 0xe1, 0x64, 0xf1, 0xe4, 0x00, 0x1e, 0xf8, 0x6c, 0x80, 0xdf, 0x70, 0xd0, 0xbf,
	0xa2, 0x41, 0x82, 0x71, 0x47, 0xaf, 0xca, 0x70, 0x3f, 0x07, 0x9e, 0x2a, 0x9c, 0x61, 0x41, 0x5d,
	0xba, 0xc9, 0xd2, 0x9f, 0xd1, 0x6b, 0x65, 0xc3, 0xd5, 0x86, 0x86, 0xe2, 0xce, 0x45, 0xc9, 0x3e,
	0x76, 0xbe, 0xd7, 0x61, 0xe1, 0x24, 0xa3, 0x25, 0x21, 0x2c, 0x96, 0xb7, 0x96, 0x3c, 0x9f, 0x9a,
	0x7d, 0xc2, 0xbb, 0x61, 0x6c, 0x56, 0x8c, 0xce, 0x44, 0x36, 0x6b, 0x64, 0x00, 0xad, 0xeb, 0x55,
	0x22, 0x1b, 0x55, 0xd6, 0x2d, 0x4b, 0xf4, 0xac, 0xfa, 0x66, 0x9a, 0x35, 0x72, 0x0a, 0x8b, 0xe5,
	0x5d, 0x99, 0xd1, 0xd4, 0x84, 0x95, 0x32, 0x1e, 0x59, 0xd9, 0x13, 0x6a, 0x15, 0xef, 0xab, 0xb5,
	0x27, 0xdf, 0x57, 0xb3, 0x26, 0xc5, 0x2a, 0x8f, 0xdf, 0x0c, 0xde, 0x09, 0x0b, 0x36, 0x43, 0xac,
	0x49, 0x33, 0x6d, 0xd6, 0x08, 0x85, 0x66, 0x31, 0xa7, 0xa4, 0x37, 0x4b, 0x80, 0xf2, 0x74, 0x1b,
	0x1b, 0x15, 0x22, 0x8b, 0x14, 0x6f, 0x43, 0x30, 0xbc, 0x60, 0x1a, 0xe0, 0x58, 0x3b, 0x3b, 0xf2,
	0x7c, 0x71, 0x99, 0xb8, 0xd6, 0x39, 0x0f, 0xed, 0x03, 0x9a, 0xf2, 0x53, 0xca, 0x3e, 0x72, 0xce,
	0xb2, 0x5f, 0xcf, 0x98, 0x47, 0xc3, 0x8b, 0x80, 0x8f, 0x37, 0x3d, 0x64, 0xca, 0x61, 0x4f, 0xf9,
	0xb1, 0xbd, 0xce, 0x4d, 0x77, 0x5e, 0x85, 0xbd, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x40, 0x76,
	0x03, 0x96, 0x02, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	// Stores data by a given key.
	// If data is already stored by the given key, nothing happens.
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error)
	// Retrieves one or more data by key(s).
	// Keys may contain wildcard values.
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	// Deletes data.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Mutates an object, but only when its current etag matches the provided
	// etag.
	// If this check fails or the item does not exist, an empty string is
	// returned.
	MutateObject(ctx context.Context, in *MutateObjectRequest, opts ...grpc.CallOption) (*MutateObjectResponse, error)
	// Produces some stats on storage
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error) {
	out := new(CreateObjectResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/CreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) MutateObject(ctx context.Context, in *MutateObjectRequest, opts ...grpc.CallOption) (*MutateObjectResponse, error) {
	out := new(MutateObjectResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/MutateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.storage.v1.Storage/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	// Stores data by a given key.
	// If data is already stored by the given key, nothing happens.
	CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error)
	// Retrieves one or more data by key(s).
	// Keys may contain wildcard values.
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	// Deletes data.
	DeleteObject(context.Context, *DeleteObjectRequest) (*empty.Empty, error)
	// Mutates an object, but only when its current etag matches the provided
	// etag.
	// If this check fails or the item does not exist, an empty string is
	// returned.
	MutateObject(context.Context, *MutateObjectRequest) (*MutateObjectResponse, error)
	// Produces some stats on storage
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_MutateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).MutateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/MutateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).MutateObject(ctx, req.(*MutateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.storage.v1.Storage/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.storage.v1.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObject",
			Handler:    _Storage_CreateObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _Storage_GetObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _Storage_DeleteObject_Handler,
		},
		{
			MethodName: "MutateObject",
			Handler:    _Storage_MutateObject_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Storage_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/storage/v1/storage.proto",
}
