// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bobsknobshop/measuring/v1/measuring.proto

package measuring

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateServiceCallRequest struct {
	// Name of the service called.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Name of the rpc called.
	// Optional if a service only has one RPC.
	RpcName              string   `protobuf:"bytes,2,opt,name=rpc_name,json=rpcName,proto3" json:"rpc_name,omitempty"`
	Request              *any.Any `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Response             *any.Any `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceCallRequest) Reset()         { *m = CreateServiceCallRequest{} }
func (m *CreateServiceCallRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceCallRequest) ProtoMessage()    {}
func (*CreateServiceCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f6cd8eb44cd1f4, []int{0}
}

func (m *CreateServiceCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceCallRequest.Unmarshal(m, b)
}
func (m *CreateServiceCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceCallRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceCallRequest.Merge(m, src)
}
func (m *CreateServiceCallRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceCallRequest.Size(m)
}
func (m *CreateServiceCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceCallRequest proto.InternalMessageInfo

func (m *CreateServiceCallRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *CreateServiceCallRequest) GetRpcName() string {
	if m != nil {
		return m.RpcName
	}
	return ""
}

func (m *CreateServiceCallRequest) GetRequest() *any.Any {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CreateServiceCallRequest) GetResponse() *any.Any {
	if m != nil {
		return m.Response
	}
	return nil
}

type CreateServiceCallResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceCallResponse) Reset()         { *m = CreateServiceCallResponse{} }
func (m *CreateServiceCallResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceCallResponse) ProtoMessage()    {}
func (*CreateServiceCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f6cd8eb44cd1f4, []int{1}
}

func (m *CreateServiceCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceCallResponse.Unmarshal(m, b)
}
func (m *CreateServiceCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceCallResponse.Marshal(b, m, deterministic)
}
func (m *CreateServiceCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceCallResponse.Merge(m, src)
}
func (m *CreateServiceCallResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceCallResponse.Size(m)
}
func (m *CreateServiceCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceCallResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateServiceCallRequest)(nil), "bobsknobshop.measuring.v1.CreateServiceCallRequest")
	proto.RegisterType((*CreateServiceCallResponse)(nil), "bobsknobshop.measuring.v1.CreateServiceCallResponse")
}

func init() {
	proto.RegisterFile("bobsknobshop/measuring/v1/measuring.proto", fileDescriptor_b3f6cd8eb44cd1f4)
}

var fileDescriptor_b3f6cd8eb44cd1f4 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x3f, 0x7f, 0x20, 0xda, 0xba, 0x2c, 0x44, 0x0c, 0x49, 0xe9, 0x50, 0x3a, 0x95, 0x01,
	0x9b, 0xb6, 0x6c, 0x4c, 0xd0, 0x85, 0x01, 0x10, 0x14, 0x89, 0x81, 0x05, 0x39, 0xd1, 0x6d, 0x1a,
	0x35, 0xb9, 0x37, 0xd8, 0x4e, 0xab, 0x6e, 0x3c, 0x01, 0x0f, 0xc4, 0xd3, 0x21, 0xc5, 0xfd, 0x83,
	0x04, 0x41, 0x62, 0xbc, 0xe7, 0x77, 0x4e, 0x74, 0x74, 0x62, 0x7e, 0x12, 0x52, 0x68, 0x66, 0x48,
	0xa1, 0x99, 0x52, 0x2e, 0x33, 0x50, 0xa6, 0xd0, 0x09, 0xc6, 0x72, 0xde, 0xdf, 0x1e, 0x22, 0xd7,
	0x64, 0xc9, 0x0b, 0xbe, 0x5a, 0xc5, 0x96, 0xce, 0xfb, 0xad, 0x76, 0x4c, 0x14, 0xa7, 0x20, 0x55,
	0x9e, 0x48, 0x85, 0x48, 0x56, 0xd9, 0x84, 0xd0, 0xb8, 0x60, 0x2b, 0x58, 0xd1, 0xf2, 0x0a, 0x8b,
	0x89, 0x54, 0xb8, 0x74, 0xa8, 0xfb, 0xc1, 0xb8, 0x3f, 0xd2, 0xa0, 0x2c, 0x3c, 0x82, 0x9e, 0x27,
	0x11, 0x8c, 0x54, 0x9a, 0x8e, 0xe1, 0xb5, 0x00, 0x63, 0xbd, 0x63, 0xbe, 0x6f, 0x9c, 0xfa, 0x82,
	0x2a, 0x03, 0x9f, 0x75, 0x58, 0xaf, 0x31, 0x6e, 0xae, 0xb4, 0x3b, 0x95, 0x81, 0x17, 0xf0, 0xba,
	0xce, 0x23, 0x87, 0xff, 0x97, 0xb8, 0xa6, 0xf3, 0xa8, 0x44, 0x82, 0xd7, 0xb4, 0xfb, 0x90, 0xbf,
	0xd3, 0x61, 0xbd, 0xe6, 0xe0, 0x50, 0xb8, 0x1e, 0x62, 0xdd, 0x43, 0x5c, 0xe2, 0x72, 0xbc, 0x36,
	0x79, 0x67, 0xbc, 0xae, 0xc1, 0xe4, 0x84, 0x06, 0xfc, 0xdd, 0x5f, 0x02, 0x1b, 0x57, 0xf7, 0x88,
	0x07, 0x3f, 0x74, 0x77, 0x70, 0xf0, 0xce, 0x78, 0xe3, 0x76, 0xbd, 0x91, 0xf7, 0xc6, 0xf8, 0xc1,
	0x37, 0xaf, 0x37, 0x14, 0x95, 0x93, 0x8a, 0xaa, 0x55, 0x5a, 0xe7, 0x7f, 0x0b, 0xad, 0xba, 0xfe,
	0xbb, 0x32, 0xbc, 0x1d, 0xa7, 0xd5, 0xd9, 0x7b, 0xf6, 0xfc, 0x10, 0x27, 0x76, 0x5a, 0x84, 0x22,
	0xa2, 0x4c, 0x5e, 0xab, 0x25, 0x3d, 0x29, 0xbc, 0x21, 0x42, 0xf7, 0xdf, 0x16, 0xa4, 0x67, 0x93,
	0x94, 0x16, 0xa7, 0x31, 0x60, 0x29, 0xc8, 0xca, 0x97, 0x73, 0xb1, 0x39, 0xc2, 0xbd, 0xd2, 0x3a,
	0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x1e, 0xcb, 0xd1, 0x67, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeasuringClient is the client API for Measuring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeasuringClient interface {
	// Posts a service call (its request and response) to BigQuery
	CreateServiceCall(ctx context.Context, in *CreateServiceCallRequest, opts ...grpc.CallOption) (*CreateServiceCallResponse, error)
}

type measuringClient struct {
	cc *grpc.ClientConn
}

func NewMeasuringClient(cc *grpc.ClientConn) MeasuringClient {
	return &measuringClient{cc}
}

func (c *measuringClient) CreateServiceCall(ctx context.Context, in *CreateServiceCallRequest, opts ...grpc.CallOption) (*CreateServiceCallResponse, error) {
	out := new(CreateServiceCallResponse)
	err := c.cc.Invoke(ctx, "/bobsknobshop.measuring.v1.Measuring/CreateServiceCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasuringServer is the server API for Measuring service.
type MeasuringServer interface {
	// Posts a service call (its request and response) to BigQuery
	CreateServiceCall(context.Context, *CreateServiceCallRequest) (*CreateServiceCallResponse, error)
}

func RegisterMeasuringServer(s *grpc.Server, srv MeasuringServer) {
	s.RegisterService(&_Measuring_serviceDesc, srv)
}

func _Measuring_CreateServiceCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasuringServer).CreateServiceCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bobsknobshop.measuring.v1.Measuring/CreateServiceCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasuringServer).CreateServiceCall(ctx, req.(*CreateServiceCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Measuring_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bobsknobshop.measuring.v1.Measuring",
	HandlerType: (*MeasuringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServiceCall",
			Handler:    _Measuring_CreateServiceCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bobsknobshop/measuring/v1/measuring.proto",
}
